### ISSUE TITLE
Do packages using the same package with an options manager interfere?

### ISSUE THREAD

**Issue by gaborcsardi** [markvanderloo/settings#1]
Sorry for not actually trying it out, hopefully you can answer this quickly. 

So the question is the following. I have a package called `pkgA` and two other packages `pkgB1` and `pkgB2`, both of which import (something from) `pkgA`. Both packages modify the settings within `pkgA`, through the exported functions of `pkgA`. Do they interfere?

I guess they do, because the actual settings are only specific to `pkgA`, but not to the packages that import `pkgA`. Right? 

If they interfere, do you think there is a way to fix this somehow?

My actual use case is a package for colored terminal output. It is typically used by other packages. These other packages can then set up their own colors and styles, but I don't want them to interfere, obviously.

Thanks for the great package!

**Comment by gaborcsardi** [comment]
Hi Mark, for the record I fixed this here: https://github.com/gaborcsardi/pkgconfig
It is a hack, but not that bad, actually.

**Comment by markvanderloo** [comment]
Oh, that's cool :+1: . It's a pretty subtle use case that I did't think of when designing 'settings'.
